In [1]:
import pandas as pd

data = {
    'name':['A', 'B', 'C' ,'D', 'E'],
    'age':[15, 26, 25, 56, 12],
    'marks':[89, 61, 55, 34, 99]
}

df = pd.DataFrame(data)
df

  name  age  marks
0    A   15     89
1    B   26     61
2    C   25     55
3    D   56     34
4    E   12     99

In [2]:
df = pd.read_csv("/content/rapido.csv")
df

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20
3,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20
4,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20
...,...,...,...,...,...,...,...,...,...,...,...,...
4606,auto,completed,Sarjapur Road,Kadubeesanahalli,105,RD8030683675488536,32.11,741.21,17.35,758.56,Amazon Pay,2024-06-29 07:41:20
4607,auto share,completed,Koramangala 9th Block,Brigade Road Residency Road,67,RD3532347680366000,44.82,202.93,19.51,222.44,Paytm,2024-07-18 01:30:20
4608,cab economy,completed,HSR Layout Sector 5 South,Nandi Hills,57,RD6855864651733693,37.36,239.09,1.36,240.45,QR scan,2024-07-17 14:25:20
4609,auto share,completed,Frazer Town,MG Road Cubbon Park,71,RD9340718348411258,13.27,124.72,23.24,147.96,phonePy,2024-07-10 02:47:20
4610,cab economy,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm,2024-07-20 07:42:20

In [ ]:
df.head(7)

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20
3,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20
4,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20
5,auto,completed,Jayanagar 8th Block,Banashankari 6th Stage,28,RD8212250057688058,34.48,729.41,33.67,763.08,Amazon Pay,2024-06-24 18:26:20
6,auto,completed,Domlur,Cooke Town,71,RD6478156857054878,22.59,620.75,36.66,657.41,GPay,2024-06-24 09:49:20

In [ ]:
df.tail(4)

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
4607,auto share,completed,Koramangala 9th Block,Brigade Road Residency Road,67,RD3532347680366000,44.82,202.93,19.51,222.44,Paytm,2024-07-18 01:30:20
4608,cab economy,completed,HSR Layout Sector 5 South,Nandi Hills,57,RD6855864651733693,37.36,239.09,1.36,240.45,QR scan,2024-07-17 14:25:20
4609,auto share,completed,Frazer Town,MG Road Cubbon Park,71,RD9340718348411258,13.27,124.72,23.24,147.96,phonePy,2024-07-10 02:47:20
4610,cab economy,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm,2024-07-20 07:42:20

In [ ]:
df.sample(5)

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
4387,bike,completed,Indiranagar 1st Stage,Jayanagar 7th Block,112,RD6604542552426724,20.23,607.12,0.98,608.10,GPay,2024-07-11 01:38:20
2306,bike lite,completed,Cubbon Road,Malleshwaram 3rd Block,108,RD9230806454926844,30.93,327.18,42.28,369.46,phonePy,2024-07-11 06:22:20
4533,bike lite,completed,Basavanagudi,Whitefield Hope Farm Junction,79,RD2066428318379885,15.37,911.10,22.76,933.86,phonePy,2024-07-19 23:25:20
3965,bike lite,completed,HSR Layout Sector 10 South,Hebbal Amruthahalli,14,RD5726665786335900,38.83,397.07,30.35,427.42,Amazon Pay,2024-06-27 15:30:20
3720,parcel,completed,Hebbal Vidyaranyapura,Ashok Nagar,56,RD8210640246702342,37.66,758.38,9.76,768.14,Paytm,2024-07-07 18:39:20

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4611 entries, 0 to 4610
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   services        4611 non-null   object
 1   ride_status     4611 non-null   object
 2   source          4611 non-null   object
 3   destination     4611 non-null   object
 4   duration        4611 non-null   int64
 5   ride_id         4611 non-null   object
 6   distance        4611 non-null   float64
 7   ride_charge     4611 non-null   float64
 8   misc_charge     4611 non-null   float64
 9   total_fare      4611 non-null   float64
 10  payment_method  4611 non-null   object
 11  datetime        4611 non-null   object
dtypes: float64(4), int64(1), object(7)
memory usage: 432.4+ KB

In [ ]:
df.describe()

          duration     distance  ride_charge  misc_charge   total_fare
count  4611.000000  4611.000000  4611.000000  4611.000000  4611.000000
mean     62.566471    25.388202   505.298315    25.206426   530.504741
std      33.403399    14.215886   285.629503    14.271037   285.880226
min       5.000000     1.010000    10.840000     0.020000    18.810000
25%      34.000000    13.020000   256.330000    12.855000   281.875000
50%      62.000000    25.220000   504.510000    25.530000   528.900000
75%      91.000000    37.660000   753.895000    37.270000   778.250000
max     120.000000    49.980000   999.700000    49.990000  1044.290000

In [3]:
df.columns

Index(['services', 'ride_status', 'source', 'destination', 'duration',
       'ride_id', 'distance', 'ride_charge', 'misc_charge', 'total_fare',
       'payment_method', 'datetime'],
      dtype='object')

In [5]:
df.shape

(4611, 12)

In [6]:
df.dtypes

services           object
ride_status        object
source             object
destination        object
duration            int64
ride_id            object
distance          float64
ride_charge       float64
misc_charge       float64
total_fare        float64
payment_method     object
datetime           object
dtype: object

In [7]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20
3,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20
4,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20

In [8]:
df.services

0              bike
1         bike lite
2            parcel
3       cab economy
4         bike lite
           ...
4606           auto
4607     auto share
4608    cab economy
4609     auto share
4610    cab economy
Name: services, Length: 4611, dtype: object

In [9]:
df.source

0            Banashankari 7th Stage
1                 Indiranagar North
2       MG Road Mahatma Gandhi Road
3                  Whitefield North
4                  Kadubeesanahalli
                   ...
4606                  Sarjapur Road
4607          Koramangala 9th Block
4608      HSR Layout Sector 5 South
4609                    Frazer Town
4610                   Hebbal North
Name: source, Length: 4611, dtype: object

In [11]:
# df.total_fare
df['total_fare']

0        95.41
1       432.45
2       275.35
3       807.70
4       692.00
         ...
4606    758.56
4607    222.44
4608    240.45
4609    147.96
4610    611.81
Name: total_fare, Length: 4611, dtype: float64

In [13]:
df

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20
3,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20
4,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20
...,...,...,...,...,...,...,...,...,...,...,...,...
4606,auto,completed,Sarjapur Road,Kadubeesanahalli,105,RD8030683675488536,32.11,741.21,17.35,758.56,Amazon Pay,2024-06-29 07:41:20
4607,auto share,completed,Koramangala 9th Block,Brigade Road Residency Road,67,RD3532347680366000,44.82,202.93,19.51,222.44,Paytm,2024-07-18 01:30:20
4608,cab economy,completed,HSR Layout Sector 5 South,Nandi Hills,57,RD6855864651733693,37.36,239.09,1.36,240.45,QR scan,2024-07-17 14:25:20
4609,auto share,completed,Frazer Town,MG Road Cubbon Park,71,RD9340718348411258,13.27,124.72,23.24,147.96,phonePy,2024-07-10 02:47:20
4610,cab economy,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm,2024-07-20 07:42:20

In [15]:
df[['source', 'destination', 'total_fare']]

                           source                  destination  total_fare
0          Banashankari 7th Stage                Richmond Road       95.41
1               Indiranagar North                Sahakar Nagar      432.45
2     MG Road Mahatma Gandhi Road             Whitefield South      275.35
3                Whitefield North        Brigade Road Eva Mall      807.70
4                Kadubeesanahalli       Banashankari 2nd Stage      692.00
...                           ...                          ...         ...
4606                Sarjapur Road             Kadubeesanahalli      758.56
4607        Koramangala 9th Block  Brigade Road Residency Road      222.44
4608    HSR Layout Sector 5 South                  Nandi Hills      240.45
4609                  Frazer Town          MG Road Cubbon Park      147.96
4610                 Hebbal North         HSR Layout Sector 10      611.81

[4611 rows x 3 columns]

In [17]:
df.head(3)

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20

In [19]:
df.distance.sum()

np.float64(117065.0)

In [21]:
df.total_fare.sum()

np.float64(2446157.36)

In [23]:
df.distance.sum()

np.float64(117065.0)

In [24]:
df.distance.min()

1.01

In [25]:
df.distance.max()

49.98

In [26]:
df.distance.mean()

np.float64(25.388202125352418)

In [28]:
df.distance.median()

25.22

In [29]:
df.head(4)

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20
3,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20

In [30]:
df.payment_method.mode()

0    QR scan
Name: payment_method, dtype: object

In [31]:
df.shape

(4611, 12)

In [32]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20
3,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20
4,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20

In [35]:
mask = df.services == 'bike'
df[mask]

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
16,bike,completed,Residency Road,Cox Town,41,RD9368948172615210,6.90,338.75,4.02,342.77,GPay,2024-07-20 05:05:20
17,bike,completed,Hebbal Dasarahalli,Malleshwaram 2nd Block,44,RD7796698949754419,30.19,405.89,21.11,427.00,Amazon Pay,2024-07-09 01:18:20
40,bike,completed,Marathahalli,Sadashivanagar,68,RD2617148786710536,23.45,89.30,5.64,94.94,GPay,2024-06-23 01:39:20
45,bike,completed,Ashok Nagar,HSR Layout Sector 1,7,RD3862156511291074,5.90,989.37,2.42,991.79,GPay,2024-06-23 21:16:20
...,...,...,...,...,...,...,...,...,...,...,...,...
4581,bike,completed,Jayanagar 3rd Block,MG Road,39,RD3714043957591991,46.74,545.46,31.26,576.72,Cash,2024-07-10 21:30:20
4585,bike,completed,Malleshwaram 10th Block,Indiranagar West,38,RD6347055613815647,20.83,975.56,6.28,981.84,Paytm,2024-07-06 10:06:20
4598,bike,completed,Ashok Nagar,BTM Layout 2nd Stage,75,RD4555404926914718,43.96,61.49,10.70,72.19,GPay,2024-07-12 10:50:20
4600,bike,completed,Brigade Road Mayo Hall,BTM Layout 1st Stage,55,RD2208153672860306,5.18,372.09,34.96,407.05,GPay,2024-07-11 19:58:20
4604,bike,completed,Kadubeesanahalli,Jayanagar 10th Block,22,RD7150131219186898,1.89,771.36,18.35,789.71,GPay,2024-06-27 21:34:20

In [36]:
df.services

0              bike
1         bike lite
2            parcel
3       cab economy
4         bike lite
           ...
4606           auto
4607     auto share
4608    cab economy
4609     auto share
4610    cab economy
Name: services, Length: 4611, dtype: object

In [40]:
mask = df.services == 'auto'
df[mask]

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
5,auto,completed,Jayanagar 8th Block,Banashankari 6th Stage,28,RD8212250057688058,34.48,729.41,33.67,763.08,Amazon Pay,2024-06-24 18:26:20
6,auto,completed,Domlur,Cooke Town,71,RD6478156857054878,22.59,620.75,36.66,657.41,GPay,2024-06-24 09:49:20
7,auto,completed,Jayanagar 6th Block East,HSR Layout Sector 5,113,RD7099134978086824,49.88,701.60,11.29,712.89,Cash,2024-07-07 20:38:20
10,auto,completed,Indiranagar North,HSR Layout Central,54,RD2034186068133556,32.65,723.76,13.58,737.34,Amazon Pay,2024-07-06 01:43:20
13,auto,completed,Electronic City Phase 2,HSR Layout Sector 8 North,7,RD5375563981393395,39.88,126.98,31.26,158.24,Amazon Pay,2024-06-27 08:26:20
...,...,...,...,...,...,...,...,...,...,...,...,...
4594,auto,completed,Electronic City Phase 3,JP Nagar Phase 4,13,RD2657875720082579,27.82,832.42,0.85,833.27,phonePy,2024-07-15 04:32:20
4596,auto,completed,Hebbal Dasarahalli,Lingarajapuram,115,RD3739522000006284,41.50,491.88,5.93,497.81,phonePy,2024-07-23 14:53:20
4602,auto,completed,Banashankari,Jayanagar 7th Block East,46,RD1585833939237997,32.19,356.00,25.69,381.69,Cash,2024-07-15 07:13:20
4605,auto,completed,Electronic City Phase 2,HSR Layout Sector 6 North,13,RD8717412868788665,40.43,594.66,15.23,609.89,Cash,2024-07-08 06:01:20
4606,auto,completed,Sarjapur Road,Kadubeesanahalli,105,RD8030683675488536,32.11,741.21,17.35,758.56,Amazon Pay,2024-06-29 07:41:20

In [43]:
mask = df.distance >= 20
df[mask]

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
5,auto,completed,Jayanagar 8th Block,Banashankari 6th Stage,28,RD8212250057688058,34.48,729.41,33.67,763.08,Amazon Pay,2024-06-24 18:26:20
6,auto,completed,Domlur,Cooke Town,71,RD6478156857054878,22.59,620.75,36.66,657.41,GPay,2024-06-24 09:49:20
7,auto,completed,Jayanagar 6th Block East,HSR Layout Sector 5,113,RD7099134978086824,49.88,701.60,11.29,712.89,Cash,2024-07-07 20:38:20
8,cab economy,completed,HSR Layout Sector 3 South,HSR Layout,99,RD2563360368286152,25.81,360.13,6.07,366.20,QR scan,2024-07-10 19:09:20
...,...,...,...,...,...,...,...,...,...,...,...,...
4603,auto share,completed,Malleshwaram 10th Block,Malleshwaram North,11,RD5756184023858085,34.60,813.99,3.59,817.58,GPay,2024-06-25 05:18:20
4605,auto,completed,Electronic City Phase 2,HSR Layout Sector 6 North,13,RD8717412868788665,40.43,594.66,15.23,609.89,Cash,2024-07-08 06:01:20
4606,auto,completed,Sarjapur Road,Kadubeesanahalli,105,RD8030683675488536,32.11,741.21,17.35,758.56,Amazon Pay,2024-06-29 07:41:20
4607,auto share,completed,Koramangala 9th Block,Brigade Road Residency Road,67,RD3532347680366000,44.82,202.93,19.51,222.44,Paytm,2024-07-18 01:30:20
4608,cab economy,completed,HSR Layout Sector 5 South,Nandi Hills,57,RD6855864651733693,37.36,239.09,1.36,240.45,QR scan,2024-07-17 14:25:20

In [44]:
df.head(4)

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20
3,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20

In [ ]:
df.total_fare.sort_values()

In [47]:
df.sort_values(by='total_fare')

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
4328,cab premium,completed,Indiranagar 2nd Stage,Banashankari 2nd Stage,7,RD5343698088473722,44.20,13.77,5.04,18.81,QR scan,2024-07-12 04:55:20
174,bike,completed,Shivajinagar,JP Nagar,14,RD1224336960663907,23.83,15.89,3.85,19.74,Cash,2024-07-23 02:47:20
1434,auto,completed,Jayanagar 8th Block,HSR Layout Sector 7,27,RD7955291901697300,32.68,13.98,6.51,20.49,Amazon Pay,2024-07-12 05:30:20
4543,auto share,completed,Cooke Town,Brigade Road Residency Road,89,RD7114496116789870,29.66,20.56,0.16,20.72,Paytm,2024-07-08 04:36:20
3353,parcel,completed,Koramangala South,Ganganagar,27,RD7371650802919391,19.07,13.85,7.36,21.21,GPay,2024-06-24 07:44:20
...,...,...,...,...,...,...,...,...,...,...,...,...
458,bike lite,completed,Brigade Road Garuda Mall,Shantinagar,93,RD9614823838452024,34.89,996.48,41.58,1038.06,Amazon Pay,2024-07-07 16:41:20
2953,auto,completed,HSR Layout Sector 4,Brigade Road East,22,RD8880235764428221,3.33,999.20,40.15,1039.35,Amazon Pay,2024-06-24 08:46:20
1462,parcel,completed,Banashankari 10th Stage,HSR Layout Sector 7,100,RD6748409250583305,12.54,996.70,42.93,1039.63,GPay,2024-07-16 02:01:20
1767,bike,completed,JP Nagar Phase 7,Whitefield Kadugodi,90,RD8880688655727686,31.94,997.92,42.21,1040.13,Amazon Pay,2024-07-11 15:20:20
1932,auto,completed,Richmond Town,Hebbal Kodigehalli,32,RD1516470641287503,13.18,997.21,47.08,1044.29,Paytm,2024-06-29 00:55:20

In [49]:
df.services.unique()

array(['bike', 'bike lite', 'parcel', 'cab economy', 'auto', 'auto share',
       'cab premium'], dtype=object)

In [53]:
df.groupby('services')['total_fare'].sum()

services
auto           391063.19
auto share     346887.26
bike           321782.00
bike lite      354782.15
cab economy    334850.51
cab premium    345342.95
parcel         351449.30
Name: total_fare, dtype: float64

In [54]:
df.groupby('services')['total_fare'].mean()

services
auto           544.656253
auto share     502.735159
bike           521.526742
bike lite      550.903960
cab economy    515.154631
cab premium    525.636149
parcel         553.463465
Name: total_fare, dtype: float64

In [55]:
df = pd.read_csv("/content/big_bazaar_sales.csv")
df

,Invoice_ID,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Quantity,Price_Per_Unit,Total_Amount,Payment_Method,Date_of_Purchase,Discount_Percent,Final_Amount,Loyalty_Customer
0,BB1001,CUST583,Male,21,Ahmedabad,Household,Doormat,10,224.45,2244.50,Cash,2025-05-06,10,2020.05,No
1,BB1002,CUST766,Male,41,Bangalore,Furniture,Table,2,270.05,540.10,Credit Card,2025-04-04,15,459.08,Yes
2,BB1003,CUST285,Male,64,Surat,Groceries,Paneer,9,436.59,3929.31,UPI,2024-12-01,20,3143.45,No
3,BB1004,CUST381,Female,30,Nagpur,Electronics,Power Bank,6,254.36,1526.16,Wallet,2024-10-03,15,1297.24,No
4,BB1005,CUST979,Male,63,Pune,Sports,Dumbbells,2,262.23,524.46,Wallet,2025-01-04,5,498.24,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,BB1996,CUST332,Female,36,Lucknow,Toys & Games,Board Game,7,474.27,3319.89,UPI,2024-07-16,20,2655.91,No
996,BB1997,CUST327,Male,36,Bhopal,Apparel,Leggings,7,437.77,3064.39,Wallet,2024-08-16,5,2911.17,Yes
997,BB1998,CUST709,Male,55,Nagpur,Furniture,Plastic Stool,1,278.20,278.20,Cash,2025-06-06,20,222.56,Yes
998,BB1999,CUST943,Male,45,Hyderabad,Stationery,Marker,8,260.94,2087.52,Wallet,2025-06-13,10,1878.77,Yes
999,BB2000,CUST799,Male,45,Thane,Kitchen,Utensils,7,89.96,629.72,Cash,2024-12-23,10,566.75,No

In [57]:
df.head(6)

,Invoice_ID,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Quantity,Price_Per_Unit,Total_Amount,Payment_Method,Date_of_Purchase,Discount_Percent,Final_Amount,Loyalty_Customer
0,BB1001,CUST583,Male,21,Ahmedabad,Household,Doormat,10,224.45,2244.50,Cash,2025-05-06,10,2020.05,No
1,BB1002,CUST766,Male,41,Bangalore,Furniture,Table,2,270.05,540.10,Credit Card,2025-04-04,15,459.08,Yes
2,BB1003,CUST285,Male,64,Surat,Groceries,Paneer,9,436.59,3929.31,UPI,2024-12-01,20,3143.45,No
3,BB1004,CUST381,Female,30,Nagpur,Electronics,Power Bank,6,254.36,1526.16,Wallet,2024-10-03,15,1297.24,No
4,BB1005,CUST979,Male,63,Pune,Sports,Dumbbells,2,262.23,524.46,Wallet,2025-01-04,5,498.24,Yes
5,BB1006,CUST482,Male,32,Thane,Electronics,Power Bank,6,419.64,2517.84,Credit Card,2024-11-26,20,2014.27,No

In [58]:
df.shape

(1000, 15)

In [59]:
df.groupby('Gender')['Final_Amount'].sum()

Gender
Female    644903.96
Male      656628.87
Name: Final_Amount, dtype: float64

In [60]:
df.groupby('Gender')['Final_Amount'].mean()

Gender
Female    1313.450020
Male      1290.037073
Name: Final_Amount, dtype: float64

In [61]:
df.head()

,Invoice_ID,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Quantity,Price_Per_Unit,Total_Amount,Payment_Method,Date_of_Purchase,Discount_Percent,Final_Amount,Loyalty_Customer
0,BB1001,CUST583,Male,21,Ahmedabad,Household,Doormat,10,224.45,2244.50,Cash,2025-05-06,10,2020.05,No
1,BB1002,CUST766,Male,41,Bangalore,Furniture,Table,2,270.05,540.10,Credit Card,2025-04-04,15,459.08,Yes
2,BB1003,CUST285,Male,64,Surat,Groceries,Paneer,9,436.59,3929.31,UPI,2024-12-01,20,3143.45,No
3,BB1004,CUST381,Female,30,Nagpur,Electronics,Power Bank,6,254.36,1526.16,Wallet,2024-10-03,15,1297.24,No
4,BB1005,CUST979,Male,63,Pune,Sports,Dumbbells,2,262.23,524.46,Wallet,2025-01-04,5,498.24,Yes

In [64]:
df.groupby('Gender')['Quantity'].sum()

Gender
Female    2751
Male      2744
Name: Quantity, dtype: int64